name: Automação E2E - ServeRest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Instalar dependências (Newman)
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Executar testes via Newman
        run: newman run serverest-collection.json -e serverest-env.json -r htmlextra --reporter-htmlextra-export ./relatorio-api.html

      - name: Salvar Relatório HTML (Artifact)
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: Relatorio-Testes-API
          path: ./relatorio-api.html
